apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    job-name: {{ .JobName }}
    app: fdb-profile-analyzer
  name: {{ .JobName }}
  namespace: {{ .Namespace }}
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: {{ .JobName }}
        app: fdb-profile-analyzer
    spec:
      containers:
        - command:
            - /bin/bash
          args:
            - -c
            - python3.9 ./transaction_profiling_analyzer.py {{ .CommandArgs }}
          env:
            - name: FDB_CLUSTER_FILE
              value: /var/dynamic-conf/fdb.cluster
            - name: FDB_NETWORK_OPTION_TRACE_ENABLE
              value: /var/log/fdb-profile-analyzer
            - name: FDB_NETWORK_OPTION_TRACE_FORMAT
              value: json
          image: fdb-profile-analyzer:latest
          imagePullPolicy: Always
          name: profile-analyzer
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/dynamic-conf
              name: config-map
              readOnly: true
            - mountPath: /var/log/fdb-profile-analyzer
              name: fdb-profile-analyzer-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 4059
        runAsGroup: 4059
        runAsUser: 4059
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: cluster-file
                path: fdb.cluster
            name: {{ .ClusterName }}-config
          name: config-map
        - emptyDir: {}
          name: dynamic-conf
        - emptyDir: {}
          name: fdb-profile-analyzer-logs
  ttlSecondsAfterFinished: 7200
